# -*- coding: utf-8 -*-
"""EDA_Ahmed Amr .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FStX5vufJLIueQLbbjQ_OOy9SoEge75Z
"""

!pip install lime shap
!pip install catboost

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score, confusion_matrix
from sklearn.inspection import permutation_importance, PartialDependenceDisplay
import shap
import lime
import lime.lime_tabular
from statsmodels.stats.outliers_influence import variance_inflation_factor
from catboost import CatBoostClassifier
from sklearn.ensemble import StackingClassifier, RandomForestClassifier, ExtraTreesClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

# 1. DATA Loading
df = pd.read_csv('/content/cardiovascular_diseases_processed.csv')
df

# EDA: Correlation Heatmap
plt.figure(figsize=(10, 6))
correlation_matrix = df.corr(numeric_only=True)
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title("Feature Correlation Heatmap (Numeric Features Only)")
plt.show()

# Identify the label column based on the dataset's specific naming convention
possible_targets = ['CARDIO_DISEASE', 'HeartDisease', 'output', 'target']
target_col = next((col for col in possible_targets if col in df.columns), None)

if target_col is None:
    raise ValueError(f"Could not find a target column. Available columns: {df.columns.tolist()}")

# 2. ENCODING: Convert text to numbers
df_encoded = pd.get_dummies(df, drop_first=True)
X = df_encoded.drop(target_col, axis=1)
y = df_encoded[target_col]

X_with_const = X.assign(const=1)
vif_data = pd.DataFrame()
vif_data["feature"] = X_with_const.columns

vif_data["VIF"] = [
    variance_inflation_factor(X_with_const.values, i)
    for i in range(len(X_with_const.columns))
]
print(vif_data.sort_values(by="VIF", ascending=False))

from google.colab import drive
drive.mount('/content/drive') # This will pop up asking for permission to connect to your Drive

# Combine X and y back together temporarily to save them
df_clean = X.copy()
df_clean[target_col] = y

# Save to your Google Drive instead of temporary storage
output_path = '/content/drive/MyDrive/cardiovascular_ready_for_models.csv'
df_clean.to_csv(output_path, index=False)

print(f"✅ Preprocessing complete! Clean data saved to your Google Drive at: {output_path}")